### ISSUE TITLE
default calenders

### ISSUE THREAD

**Issue by JohnV7** [ctcode/visual-planner#3]
Very nice tool!
I'm not familiar with js, how can I set which calendars to display by default?
Can I put somewhere sth like this?

`if calendar_name=='calendar1'  or calendar_name=='calendar2' then display`

and uncheck all other calendars?

**Comment by ctcode** [comment]
Can you be more specific? Do you want to set which calendars are initially loaded by the app or which calendars are loaded and then hidden using the calendar buttons at the bottom of the page? Only calendars which are selected and visible in Google Calendar are initially loaded by the app if that is what you wish to achieve.

**Comment by JohnV7** [comment]
I would like to achieve the former. To load all calender's that I have, but then to hide all but two as a default view. The hidden ones should be available for activation using the calendar buttons at the bottom of the page.

**Comment by ctcode** [comment]
To set the initial state of the calendar buttons, you can simulate a mouse click after each button is created as follows :
```javascript
VipCalendarBar.prototype.rcvCal = function(cal)
{
	... create calendar button ...
	
	if (cal.name == "xyz")
		vcb.onclickCalBtn();  // initial button state = 'checked'
}
```
Functionality to persist the state of the calendar buttons will be added at some point in the future.

**Comment by JohnV7** [comment]
ok, thanks! I will try it out.

**Comment by ctcode** [comment]
Functionality to persist the state of the calendar buttons has now been added so that the hidden calendars remain hidden when the page is reloaded. The button state is saved locally so does not persist across devices.
