### ISSUE TITLE
Scrolling is light speed - slow it down?

### ISSUE THREAD

**Issue by Doofitator** [ctcode/visual-planner#4]
Brilliant calendar. Absolutely love it, aside from one hitch - navigation works great with arrow keys, however my first instinct was scrolling, and in half a second of moving my fingers I was a decade into the past. I believe it needs to be slowed down.

**Comment by ctcode** [comment]
What kind of device and what scrolling method are you using? Also, which browser/OS?

**Comment by Doofitator** [comment]
I'm using an iMac currently. Apple Magic Trackpad & two finger scrolling. Haven't updated in a while so still running MacOS Sierra (10.12.6), & I use Google Chrome. Found the same issue on my late 2011 Macbook Pro & Lenovo Yoga 11e, too. MBP runs High Sierra, magic trackpad & two finger scroll, Yoga runs Windows 10 1803 & windows precision touchpad, two finger scroll. All Google Chrome.

Edit: Is it set up for scrolling with a mouse wheel perhaps? One click of the wheel = one hit of the arrow key? Perhaps it needs to be modified to play nice with trackpads too. I'll go find a mouse for you and see if it works with that.

**Comment by Doofitator** [comment]
can confirm no issues with wired mouse.

**Comment by ctcode** [comment]
Yes it is set up to respond to mouse wheel events: one click = one month scroll.
I'll try and find a way of limiting the rate at which wheel events are processed.

**Comment by Doofitator** [comment]
That sounds like it might be the best way of doing it. There really shouldn't be much reason for a mousewheel to move more than ~2 years, so lowering the speed at which scrolling is processed shouldn't hurt the UX when there's a mouse, and should help significantly when a trackpad is involved.

**Comment by ctcode** [comment]
Wheel scrolling events have now been throttled to a maximum of 10/s which should still be plenty fast enough. Has it slowed your trackpad?

**Comment by Doofitator** [comment]
Yes - It has slowed it down enough to control it, however the movements are very precise. I can manage to move one month forward or backward with a little bit of practice, but it's about a millimeter of movement of my fingers either way, and I feel like the travel has to be more in order for it to be comfortable.

Don't get me wrong - It's good enough to be useable for me, and I would be happy to close this issue, but if it hasn't affected the mouse UX too badly, the dial could be turned up a bit further I feel.

**Comment by ctcode** [comment]
OK, the interval is now set at 150ms which is about the limit before the lag becomes noticeable.

**Comment by Doofitator** [comment]
That's definitely useable. A great improvement. Thanks muchly.
